networks:
  dbwebb:

services:
  server:
    image: "emelieklund/vteam-server:1.0"
    container_name: "server"
    ports:
      - "1337:1337"
    networks:
      dbwebb:
    volumes:
      - "./data/:/data/"
    restart:
      "always"
  client:
    image: "emelieklund/vteam-client:1.0"
    container_name: "client"
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/client/"
    networks:
      dbwebb:
