networks:
  dbwebb:

services:
  server:
    image: "anja22/vteams-backend"
    container_name: "server"
    ports:
      - "1337:1337"
    networks:
      dbwebb:
    volumes:
      - "./server/:/server/"
  client:
    image: "emelieklund/vteam-client:1.0"
    container_name: "client"
    ports:
      - "3000:3000"
    volumes:
      - "./client/:/client/"
    networks:
      dbwebb:
